// Mocks generated by Mockito 5.4.6 from annotations
// in opennutritracker/test/unit_test/get_macro_goal_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:opennutritracker/core/data/repository/config_repository.dart'
    as _i3;
import 'package:opennutritracker/core/domain/entity/app_theme_entity.dart'
    as _i5;
import 'package:opennutritracker/core/domain/entity/config_entity.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConfigEntity_0 extends _i1.SmartFake implements _i2.ConfigEntity {
  _FakeConfigEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigRepository extends _i1.Mock implements _i3.ConfigRepository {
  MockConfigRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> updateConfig(_i2.ConfigEntity? configEntity) =>
      (super.noSuchMethod(
            Invocation.method(#updateConfig, [configEntity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setConfigDisclaimer(bool? hasAcceptedDisclaimer) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigDisclaimer, [hasAcceptedDisclaimer]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setConfigHasAcceptedAnonymousData(
    bool? hasAcceptedAnonymousData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigHasAcceptedAnonymousData, [
              hasAcceptedAnonymousData,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> getConfigHasAcceptedAnonymousData() =>
      (super.noSuchMethod(
            Invocation.method(#getConfigHasAcceptedAnonymousData, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i5.AppThemeEntity> getConfigAppTheme() =>
      (super.noSuchMethod(
            Invocation.method(#getConfigAppTheme, []),
            returnValue: _i4.Future<_i5.AppThemeEntity>.value(
              _i5.AppThemeEntity.light,
            ),
          )
          as _i4.Future<_i5.AppThemeEntity>);

  @override
  _i4.Future<void> setConfigAppTheme(_i5.AppThemeEntity? appTheme) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigAppTheme, [appTheme]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ConfigEntity> getConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getConfig, []),
            returnValue: _i4.Future<_i2.ConfigEntity>.value(
              _FakeConfigEntity_0(this, Invocation.method(#getConfig, [])),
            ),
          )
          as _i4.Future<_i2.ConfigEntity>);

  @override
  _i4.Future<bool> configInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#configInitialized, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> initializeConfig() =>
      (super.noSuchMethod(
            Invocation.method(#initializeConfig, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setConfigUsesImperialUnits(bool? usesImperialUnits) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigUsesImperialUnits, [usesImperialUnits]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<double> getConfigKcalAdjustment() =>
      (super.noSuchMethod(
            Invocation.method(#getConfigKcalAdjustment, []),
            returnValue: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);

  @override
  _i4.Future<void> setConfigKcalAdjustment(double? kcalAdjustment) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigKcalAdjustment, [kcalAdjustment]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserMacroPct(
    double? carbs,
    double? protein,
    double? fat,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setUserMacroPct, [carbs, protein, fat]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<double> getExerciseMultiplier() =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseMultiplier, []),
            returnValue: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);

  @override
  _i4.Future<void> setExerciseMultiplier(double? multiplier) =>
      (super.noSuchMethod(
            Invocation.method(#setExerciseMultiplier, [multiplier]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> getHasAskedHealthPermission() =>
      (super.noSuchMethod(
            Invocation.method(#getHasAskedHealthPermission, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> setHasAskedHealthPermission(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setHasAskedHealthPermission, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> getNotifEnabled(String? slot) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifEnabled, [slot]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> setNotifEnabled(String? slot, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setNotifEnabled, [slot, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getNotifHour(String? slot) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifHour, [slot]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getNotifMinute(String? slot) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifMinute, [slot]),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> setNotifTime(String? slot, int? hour, int? minute) =>
      (super.noSuchMethod(
            Invocation.method(#setNotifTime, [slot, hour, minute]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getDayBoundaryHour() =>
      (super.noSuchMethod(
            Invocation.method(#getDayBoundaryHour, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> setDayBoundaryHour(int? hour) =>
      (super.noSuchMethod(
            Invocation.method(#setDayBoundaryHour, [hour]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> getMacroMode() =>
      (super.noSuchMethod(
            Invocation.method(#getMacroMode, []),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getMacroMode, []),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> setMacroMode(String? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setMacroMode, [mode]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<double?> getFixedProteinGrams() =>
      (super.noSuchMethod(
            Invocation.method(#getFixedProteinGrams, []),
            returnValue: _i4.Future<double?>.value(),
          )
          as _i4.Future<double?>);

  @override
  _i4.Future<void> setFixedProteinGrams(double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setFixedProteinGrams, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<double?> getFixedCarbsGrams() =>
      (super.noSuchMethod(
            Invocation.method(#getFixedCarbsGrams, []),
            returnValue: _i4.Future<double?>.value(),
          )
          as _i4.Future<double?>);

  @override
  _i4.Future<void> setFixedCarbsGrams(double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setFixedCarbsGrams, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<double?> getFixedFatGrams() =>
      (super.noSuchMethod(
            Invocation.method(#getFixedFatGrams, []),
            returnValue: _i4.Future<double?>.value(),
          )
          as _i4.Future<double?>);

  @override
  _i4.Future<void> setFixedFatGrams(double? value) =>
      (super.noSuchMethod(
            Invocation.method(#setFixedFatGrams, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
