// Mocks generated by Mockito 5.4.6 from annotations
// in opennutritracker/test/features/home/home_bloc_refresh_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:opennutritracker/core/data/repository/config_repository.dart'
    as _i22;
import 'package:opennutritracker/core/data/repository/health_repository.dart'
    as _i21;
import 'package:opennutritracker/core/domain/entity/app_theme_entity.dart'
    as _i6;
import 'package:opennutritracker/core/domain/entity/config_entity.dart' as _i2;
import 'package:opennutritracker/core/domain/entity/intake_entity.dart' as _i8;
import 'package:opennutritracker/core/domain/entity/tracked_day_entity.dart'
    as _i20;
import 'package:opennutritracker/core/domain/entity/user_activity_entity.dart'
    as _i13;
import 'package:opennutritracker/core/domain/entity/user_entity.dart' as _i17;
import 'package:opennutritracker/core/domain/usecase/add_config_usecase.dart'
    as _i5;
import 'package:opennutritracker/core/domain/usecase/add_tracked_day_usecase.dart'
    as _i15;
import 'package:opennutritracker/core/domain/usecase/delete_intake_usecase.dart'
    as _i10;
import 'package:opennutritracker/core/domain/usecase/delete_user_activity_usecase.dart'
    as _i14;
import 'package:opennutritracker/core/domain/usecase/get_config_usecase.dart'
    as _i3;
import 'package:opennutritracker/core/domain/usecase/get_intake_usecase.dart'
    as _i7;
import 'package:opennutritracker/core/domain/usecase/get_kcal_goal_usecase.dart'
    as _i16;
import 'package:opennutritracker/core/domain/usecase/get_macro_goal_usecase.dart'
    as _i18;
import 'package:opennutritracker/core/domain/usecase/get_tracked_day_usecase.dart'
    as _i19;
import 'package:opennutritracker/core/domain/usecase/get_user_activity_usecase.dart'
    as _i12;
import 'package:opennutritracker/core/domain/usecase/update_intake_usecase.dart'
    as _i11;
import 'package:opennutritracker/features/add_meal/domain/entity/meal_entity.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConfigEntity_0 extends _i1.SmartFake implements _i2.ConfigEntity {
  _FakeConfigEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetConfigUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetConfigUsecase extends _i1.Mock implements _i3.GetConfigUsecase {
  @override
  _i4.Future<_i2.ConfigEntity> getConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getConfig, []),
            returnValue: _i4.Future<_i2.ConfigEntity>.value(
              _FakeConfigEntity_0(this, Invocation.method(#getConfig, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ConfigEntity>.value(
              _FakeConfigEntity_0(this, Invocation.method(#getConfig, [])),
            ),
          )
          as _i4.Future<_i2.ConfigEntity>);
}

/// A class which mocks [AddConfigUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddConfigUsecase extends _i1.Mock implements _i5.AddConfigUsecase {
  @override
  _i4.Future<void> addConfig(_i2.ConfigEntity? configEntity) =>
      (super.noSuchMethod(
            Invocation.method(#addConfig, [configEntity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setConfigDisclaimer(bool? hasAcceptedDisclaimer) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigDisclaimer, [hasAcceptedDisclaimer]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setConfigHasAcceptedAnonymousData(
    bool? hasAcceptedAnonymousData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigHasAcceptedAnonymousData, [
              hasAcceptedAnonymousData,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setConfigAppTheme(_i6.AppThemeEntity? appTheme) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigAppTheme, [appTheme]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setConfigUsesImperialUnits(bool? usesImperialUnits) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigUsesImperialUnits, [usesImperialUnits]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setConfigKcalAdjustment(double? kcalAdjustment) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigKcalAdjustment, [kcalAdjustment]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setConfigMacroGoalPct(
    double? carbGoalPct,
    double? proteinGoalPct,
    double? fatPctGoal,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigMacroGoalPct, [
              carbGoalPct,
              proteinGoalPct,
              fatPctGoal,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GetIntakeUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetIntakeUsecase extends _i1.Mock implements _i7.GetIntakeUsecase {
  @override
  _i4.Future<List<_i8.IntakeEntity>> getBreakfastIntakeByDay(dynamic day) =>
      (super.noSuchMethod(
            Invocation.method(#getBreakfastIntakeByDay, [day]),
            returnValue: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
          )
          as _i4.Future<List<_i8.IntakeEntity>>);

  @override
  _i4.Future<List<_i8.IntakeEntity>> getTodayBreakfastIntake() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayBreakfastIntake, []),
            returnValue: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
          )
          as _i4.Future<List<_i8.IntakeEntity>>);

  @override
  _i4.Future<List<_i8.IntakeEntity>> getLunchIntakeByDay(dynamic day) =>
      (super.noSuchMethod(
            Invocation.method(#getLunchIntakeByDay, [day]),
            returnValue: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
          )
          as _i4.Future<List<_i8.IntakeEntity>>);

  @override
  _i4.Future<List<_i8.IntakeEntity>> getTodayLunchIntake() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayLunchIntake, []),
            returnValue: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
          )
          as _i4.Future<List<_i8.IntakeEntity>>);

  @override
  _i4.Future<List<_i8.IntakeEntity>> getDinnerIntakeByDay(dynamic day) =>
      (super.noSuchMethod(
            Invocation.method(#getDinnerIntakeByDay, [day]),
            returnValue: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
          )
          as _i4.Future<List<_i8.IntakeEntity>>);

  @override
  _i4.Future<List<_i8.IntakeEntity>> getTodayDinnerIntake() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayDinnerIntake, []),
            returnValue: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
          )
          as _i4.Future<List<_i8.IntakeEntity>>);

  @override
  _i4.Future<List<_i8.IntakeEntity>> getSnackIntakeByDay(dynamic day) =>
      (super.noSuchMethod(
            Invocation.method(#getSnackIntakeByDay, [day]),
            returnValue: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
          )
          as _i4.Future<List<_i8.IntakeEntity>>);

  @override
  _i4.Future<List<_i8.IntakeEntity>> getTodaySnackIntake() =>
      (super.noSuchMethod(
            Invocation.method(#getTodaySnackIntake, []),
            returnValue: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
          )
          as _i4.Future<List<_i8.IntakeEntity>>);

  @override
  _i4.Future<List<_i8.IntakeEntity>> getRecentIntake() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentIntake, []),
            returnValue: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i8.IntakeEntity>>.value(
              <_i8.IntakeEntity>[],
            ),
          )
          as _i4.Future<List<_i8.IntakeEntity>>);

  @override
  _i4.Future<_i8.IntakeEntity?> getIntakeById(String? intakeId) =>
      (super.noSuchMethod(
            Invocation.method(#getIntakeById, [intakeId]),
            returnValue: _i4.Future<_i8.IntakeEntity?>.value(),
            returnValueForMissingStub: _i4.Future<_i8.IntakeEntity?>.value(),
          )
          as _i4.Future<_i8.IntakeEntity?>);

  @override
  _i4.Future<List<_i9.MealEntity>> getFavouriteMeals() =>
      (super.noSuchMethod(
            Invocation.method(#getFavouriteMeals, []),
            returnValue: _i4.Future<List<_i9.MealEntity>>.value(
              <_i9.MealEntity>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i9.MealEntity>>.value(
              <_i9.MealEntity>[],
            ),
          )
          as _i4.Future<List<_i9.MealEntity>>);

  @override
  _i4.Future<void> toggleFavourite(String? foodItemId, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavourite, [foodItemId, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [DeleteIntakeUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteIntakeUsecase extends _i1.Mock
    implements _i10.DeleteIntakeUsecase {
  @override
  _i4.Future<void> deleteIntake(_i8.IntakeEntity? intakeEntity) =>
      (super.noSuchMethod(
            Invocation.method(#deleteIntake, [intakeEntity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [UpdateIntakeUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateIntakeUsecase extends _i1.Mock
    implements _i11.UpdateIntakeUsecase {
  @override
  _i4.Future<_i8.IntakeEntity?> updateIntake(
    String? intakeId,
    Map<String, dynamic>? intakeFields,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateIntake, [intakeId, intakeFields]),
            returnValue: _i4.Future<_i8.IntakeEntity?>.value(),
            returnValueForMissingStub: _i4.Future<_i8.IntakeEntity?>.value(),
          )
          as _i4.Future<_i8.IntakeEntity?>);
}

/// A class which mocks [GetUserActivityUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserActivityUsecase extends _i1.Mock
    implements _i12.GetUserActivityUsecase {
  @override
  _i4.Future<List<_i13.UserActivityEntity>> getTodayUserActivity() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayUserActivity, []),
            returnValue: _i4.Future<List<_i13.UserActivityEntity>>.value(
              <_i13.UserActivityEntity>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i13.UserActivityEntity>>.value(
                  <_i13.UserActivityEntity>[],
                ),
          )
          as _i4.Future<List<_i13.UserActivityEntity>>);

  @override
  _i4.Future<List<_i13.UserActivityEntity>> getUserActivityByDay(
    DateTime? day,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserActivityByDay, [day]),
            returnValue: _i4.Future<List<_i13.UserActivityEntity>>.value(
              <_i13.UserActivityEntity>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i13.UserActivityEntity>>.value(
                  <_i13.UserActivityEntity>[],
                ),
          )
          as _i4.Future<List<_i13.UserActivityEntity>>);

  @override
  _i4.Future<List<_i13.UserActivityEntity>> getRecentUserActivity() =>
      (super.noSuchMethod(
            Invocation.method(#getRecentUserActivity, []),
            returnValue: _i4.Future<List<_i13.UserActivityEntity>>.value(
              <_i13.UserActivityEntity>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i13.UserActivityEntity>>.value(
                  <_i13.UserActivityEntity>[],
                ),
          )
          as _i4.Future<List<_i13.UserActivityEntity>>);
}

/// A class which mocks [DeleteUserActivityUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeleteUserActivityUsecase extends _i1.Mock
    implements _i14.DeleteUserActivityUsecase {
  @override
  _i4.Future<void> deleteUserActivity(
    _i13.UserActivityEntity? activityEntity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUserActivity, [activityEntity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [AddTrackedDayUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddTrackedDayUsecase extends _i1.Mock
    implements _i15.AddTrackedDayUsecase {
  @override
  _i4.Future<void> updateDayCalorieGoal(DateTime? day, double? calorieGoal) =>
      (super.noSuchMethod(
            Invocation.method(#updateDayCalorieGoal, [day, calorieGoal]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> increaseDayCalorieGoal(DateTime? day, double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#increaseDayCalorieGoal, [day, amount]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reduceDayCalorieGoal(DateTime? day, double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#reduceDayCalorieGoal, [day, amount]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> hasTrackedDay(DateTime? day) =>
      (super.noSuchMethod(
            Invocation.method(#hasTrackedDay, [day]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> addNewTrackedDay(
    DateTime? day,
    double? totalKcalGoal,
    double? totalCarbsGoal,
    double? totalFatGoal,
    double? totalProteinGoal,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addNewTrackedDay, [
              day,
              totalKcalGoal,
              totalCarbsGoal,
              totalFatGoal,
              totalProteinGoal,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addDayCaloriesTracked(
    DateTime? day,
    double? caloriesTracked,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addDayCaloriesTracked, [day, caloriesTracked]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeDayCaloriesTracked(
    DateTime? day,
    double? caloriesTracked,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeDayCaloriesTracked, [
              day,
              caloriesTracked,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateDayMacroGoals(
    DateTime? day, {
    double? carbsGoal,
    double? fatGoal,
    double? proteinGoal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateDayMacroGoals,
              [day],
              {
                #carbsGoal: carbsGoal,
                #fatGoal: fatGoal,
                #proteinGoal: proteinGoal,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> increaseDayMacroGoals(
    DateTime? day, {
    double? carbsAmount,
    double? fatAmount,
    double? proteinAmount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #increaseDayMacroGoals,
              [day],
              {
                #carbsAmount: carbsAmount,
                #fatAmount: fatAmount,
                #proteinAmount: proteinAmount,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reduceDayMacroGoals(
    DateTime? day, {
    double? carbsAmount,
    double? fatAmount,
    double? proteinAmount,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #reduceDayMacroGoals,
              [day],
              {
                #carbsAmount: carbsAmount,
                #fatAmount: fatAmount,
                #proteinAmount: proteinAmount,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addDayMacrosTracked(
    DateTime? day, {
    double? carbsTracked,
    double? fatTracked,
    double? proteinTracked,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addDayMacrosTracked,
              [day],
              {
                #carbsTracked: carbsTracked,
                #fatTracked: fatTracked,
                #proteinTracked: proteinTracked,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeDayMacrosTracked(
    DateTime? day, {
    double? carbsTracked,
    double? fatTracked,
    double? proteinTracked,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #removeDayMacrosTracked,
              [day],
              {
                #carbsTracked: carbsTracked,
                #fatTracked: fatTracked,
                #proteinTracked: proteinTracked,
              },
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDayIfEmpty(DateTime? day) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDayIfEmpty, [day]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [GetKcalGoalUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetKcalGoalUsecase extends _i1.Mock
    implements _i16.GetKcalGoalUsecase {
  @override
  _i4.Future<double> getKcalGoal({
    _i17.UserEntity? userEntity,
    double? totalKcalActivitiesParam,
    double? kcalUserAdjustment,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getKcalGoal, [], {
              #userEntity: userEntity,
              #totalKcalActivitiesParam: totalKcalActivitiesParam,
              #kcalUserAdjustment: kcalUserAdjustment,
            }),
            returnValue: _i4.Future<double>.value(0.0),
            returnValueForMissingStub: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);
}

/// A class which mocks [GetMacroGoalUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMacroGoalUsecase extends _i1.Mock
    implements _i18.GetMacroGoalUsecase {
  @override
  _i4.Future<double> getCarbsGoal(double? totalCalorieGoal) =>
      (super.noSuchMethod(
            Invocation.method(#getCarbsGoal, [totalCalorieGoal]),
            returnValue: _i4.Future<double>.value(0.0),
            returnValueForMissingStub: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);

  @override
  _i4.Future<double> getFatsGoal(double? totalCalorieGoal) =>
      (super.noSuchMethod(
            Invocation.method(#getFatsGoal, [totalCalorieGoal]),
            returnValue: _i4.Future<double>.value(0.0),
            returnValueForMissingStub: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);

  @override
  _i4.Future<double> getProteinsGoal(double? totalCalorieGoal) =>
      (super.noSuchMethod(
            Invocation.method(#getProteinsGoal, [totalCalorieGoal]),
            returnValue: _i4.Future<double>.value(0.0),
            returnValueForMissingStub: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);
}

/// A class which mocks [GetTrackedDayUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTrackedDayUsecase extends _i1.Mock
    implements _i19.GetTrackedDayUsecase {
  @override
  _i4.Future<_i20.TrackedDayEntity?> getTrackedDay(DateTime? day) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackedDay, [day]),
            returnValue: _i4.Future<_i20.TrackedDayEntity?>.value(),
            returnValueForMissingStub:
                _i4.Future<_i20.TrackedDayEntity?>.value(),
          )
          as _i4.Future<_i20.TrackedDayEntity?>);

  @override
  _i4.Future<List<_i20.TrackedDayEntity>> getTrackedDaysByRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTrackedDaysByRange, [start, end]),
            returnValue: _i4.Future<List<_i20.TrackedDayEntity>>.value(
              <_i20.TrackedDayEntity>[],
            ),
            returnValueForMissingStub:
                _i4.Future<List<_i20.TrackedDayEntity>>.value(
                  <_i20.TrackedDayEntity>[],
                ),
          )
          as _i4.Future<List<_i20.TrackedDayEntity>>);
}

/// A class which mocks [HealthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHealthRepository extends _i1.Mock implements _i21.HealthRepository {
  @override
  _i4.Future<bool> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> hasPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<double> fetchAndCacheActiveCalories() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAndCacheActiveCalories, []),
            returnValue: _i4.Future<double>.value(0.0),
            returnValueForMissingStub: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);

  @override
  _i4.Future<(double, DateTime?)> getCachedActiveCalories() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedActiveCalories, []),
            returnValue: _i4.Future<(double, DateTime?)>.value((0.0, null)),
            returnValueForMissingStub: _i4.Future<(double, DateTime?)>.value((
              0.0,
              null,
            )),
          )
          as _i4.Future<(double, DateTime?)>);
}

/// A class which mocks [ConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigRepository extends _i1.Mock implements _i22.ConfigRepository {
  @override
  _i4.Future<void> updateConfig(_i2.ConfigEntity? configEntity) =>
      (super.noSuchMethod(
            Invocation.method(#updateConfig, [configEntity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setConfigDisclaimer(bool? hasAcceptedDisclaimer) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigDisclaimer, [hasAcceptedDisclaimer]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setConfigHasAcceptedAnonymousData(
    bool? hasAcceptedAnonymousData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigHasAcceptedAnonymousData, [
              hasAcceptedAnonymousData,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> getConfigHasAcceptedAnonymousData() =>
      (super.noSuchMethod(
            Invocation.method(#getConfigHasAcceptedAnonymousData, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i6.AppThemeEntity> getConfigAppTheme() =>
      (super.noSuchMethod(
            Invocation.method(#getConfigAppTheme, []),
            returnValue: _i4.Future<_i6.AppThemeEntity>.value(
              _i6.AppThemeEntity.light,
            ),
            returnValueForMissingStub: _i4.Future<_i6.AppThemeEntity>.value(
              _i6.AppThemeEntity.light,
            ),
          )
          as _i4.Future<_i6.AppThemeEntity>);

  @override
  _i4.Future<void> setConfigAppTheme(_i6.AppThemeEntity? appTheme) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigAppTheme, [appTheme]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ConfigEntity> getConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getConfig, []),
            returnValue: _i4.Future<_i2.ConfigEntity>.value(
              _FakeConfigEntity_0(this, Invocation.method(#getConfig, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ConfigEntity>.value(
              _FakeConfigEntity_0(this, Invocation.method(#getConfig, [])),
            ),
          )
          as _i4.Future<_i2.ConfigEntity>);

  @override
  _i4.Future<bool> configInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#configInitialized, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> initializeConfig() =>
      (super.noSuchMethod(
            Invocation.method(#initializeConfig, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setConfigUsesImperialUnits(bool? usesImperialUnits) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigUsesImperialUnits, [usesImperialUnits]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<double> getConfigKcalAdjustment() =>
      (super.noSuchMethod(
            Invocation.method(#getConfigKcalAdjustment, []),
            returnValue: _i4.Future<double>.value(0.0),
            returnValueForMissingStub: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);

  @override
  _i4.Future<void> setConfigKcalAdjustment(double? kcalAdjustment) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigKcalAdjustment, [kcalAdjustment]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setUserMacroPct(
    double? carbs,
    double? protein,
    double? fat,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setUserMacroPct, [carbs, protein, fat]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<double> getExerciseMultiplier() =>
      (super.noSuchMethod(
            Invocation.method(#getExerciseMultiplier, []),
            returnValue: _i4.Future<double>.value(0.0),
            returnValueForMissingStub: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);

  @override
  _i4.Future<void> setExerciseMultiplier(double? multiplier) =>
      (super.noSuchMethod(
            Invocation.method(#setExerciseMultiplier, [multiplier]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> getHasAskedHealthPermission() =>
      (super.noSuchMethod(
            Invocation.method(#getHasAskedHealthPermission, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> setHasAskedHealthPermission(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setHasAskedHealthPermission, [value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> getNotifEnabled(String? slot) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifEnabled, [slot]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> setNotifEnabled(String? slot, bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setNotifEnabled, [slot, value]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getNotifHour(String? slot) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifHour, [slot]),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<int> getNotifMinute(String? slot) =>
      (super.noSuchMethod(
            Invocation.method(#getNotifMinute, [slot]),
            returnValue: _i4.Future<int>.value(0),
            returnValueForMissingStub: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> setNotifTime(String? slot, int? hour, int? minute) =>
      (super.noSuchMethod(
            Invocation.method(#setNotifTime, [slot, hour, minute]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
